//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 10:05:41 AM CEST 
//


package org.kisst.caas._2_0.template;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The details of a data source
 * 
 * <p>Java class for DSO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DSO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datasourceconfiguration" type="{http://caas.kisst.org/2.0/template}DataSourceConfiguration"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://caas.kisst.org/2.0/template}DSOType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DSO", propOrder = {
    "datasourceconfiguration"
})
public class DSO {

    @XmlElement(required = true)
    protected DataSourceConfiguration datasourceconfiguration;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "desc", required = true)
    protected String desc;
    @XmlAttribute(name = "type")
    protected DSOType type;

    /**
     * Gets the value of the datasourceconfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link DataSourceConfiguration }
     *     
     */
    public DataSourceConfiguration getDatasourceconfiguration() {
        return datasourceconfiguration;
    }

    /**
     * Sets the value of the datasourceconfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSourceConfiguration }
     *     
     */
    public void setDatasourceconfiguration(DataSourceConfiguration value) {
        this.datasourceconfiguration = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link DSOType }
     *     
     */
    public DSOType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSOType }
     *     
     */
    public void setType(DSOType value) {
        this.type = value;
    }

}
