//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 10:05:41 AM CEST 
//


package org.kisst.caas._2_0.template;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kisst.caas._2_0.template package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Org_QNAME = new QName("http://caas.kisst.org/2.0/template", "org");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kisst.caas._2_0.template
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Assignment }
     * 
     */
    public Assignment createAssignment() {
        return new Assignment();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link WSI }
     * 
     */
    public WSI createWSI() {
        return new WSI();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link ConnectionPoint }
     * 
     */
    public ConnectionPoint createConnectionPoint() {
        return new ConnectionPoint();
    }

    /**
     * Create an instance of {@link DataSourceConfiguration }
     * 
     */
    public DataSourceConfiguration createDataSourceConfiguration() {
        return new DataSourceConfiguration();
    }

    /**
     * Create an instance of {@link ServiceContainer }
     * 
     */
    public ServiceContainer createServiceContainer() {
        return new ServiceContainer();
    }

    /**
     * Create an instance of {@link Strategy }
     * 
     */
    public Strategy createStrategy() {
        return new Strategy();
    }

    /**
     * Create an instance of {@link ServiceGroup }
     * 
     */
    public ServiceGroup createServiceGroup() {
        return new ServiceGroup();
    }

    /**
     * Create an instance of {@link BusSoapProcessorConfiguration }
     * 
     */
    public BusSoapProcessorConfiguration createBusSoapProcessorConfiguration() {
        return new BusSoapProcessorConfiguration();
    }

    /**
     * Create an instance of {@link XMLStoreObject }
     * 
     */
    public XMLStoreObject createXMLStoreObject() {
        return new XMLStoreObject();
    }

    /**
     * Create an instance of {@link DSO }
     * 
     */
    public DSO createDSO() {
        return new DSO();
    }

    /**
     * Create an instance of {@link BusSoapNodeConfiguration }
     * 
     */
    public BusSoapNodeConfiguration createBusSoapNodeConfiguration() {
        return new BusSoapNodeConfiguration();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://caas.kisst.org/2.0/template", name = "org")
    public JAXBElement<Organization> createOrg(Organization value) {
        return new JAXBElement<Organization>(_Org_QNAME, Organization.class, null, value);
    }

}
