//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 10:05:41 AM CEST 
//


package org.kisst.caas._2_0.template;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Holds the template for the entire organization
 * 
 * <p>Java class for Organization complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Organization">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="package" type="{http://caas.kisst.org/2.0/template}Package" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dso" type="{http://caas.kisst.org/2.0/template}DSO" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="xmlstoreobject" type="{http://caas.kisst.org/2.0/template}XMLStoreObject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="role" type="{http://caas.kisst.org/2.0/template}Role" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="user" type="{http://caas.kisst.org/2.0/template}User" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="servicegroup" type="{http://caas.kisst.org/2.0/template}ServiceGroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="org" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organization", propOrder = {
    "_package",
    "dso",
    "xmlstoreobject",
    "role",
    "user",
    "servicegroup"
})
public class Organization {

    @XmlElement(name = "package")
    protected List<Package> _package;
    protected List<DSO> dso;
    protected List<XMLStoreObject> xmlstoreobject;
    protected List<Role> role;
    protected List<User> user;
    protected List<ServiceGroup> servicegroup;
    @XmlAttribute(name = "org", required = true)
    protected String org;

    /**
     * Gets the value of the package property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the package property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Package }
     * 
     * 
     */
    public List<Package> getPackage() {
        if (_package == null) {
            _package = new ArrayList<Package>();
        }
        return this._package;
    }

    /**
     * Gets the value of the dso property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dso property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDso().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DSO }
     * 
     * 
     */
    public List<DSO> getDso() {
        if (dso == null) {
            dso = new ArrayList<DSO>();
        }
        return this.dso;
    }

    /**
     * Gets the value of the xmlstoreobject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xmlstoreobject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXmlstoreobject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLStoreObject }
     * 
     * 
     */
    public List<XMLStoreObject> getXmlstoreobject() {
        if (xmlstoreobject == null) {
            xmlstoreobject = new ArrayList<XMLStoreObject>();
        }
        return this.xmlstoreobject;
    }

    /**
     * Gets the value of the role property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the role property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Role }
     * 
     * 
     */
    public List<Role> getRole() {
        if (role == null) {
            role = new ArrayList<Role>();
        }
        return this.role;
    }

    /**
     * Gets the value of the user property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the user property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link User }
     * 
     * 
     */
    public List<User> getUser() {
        if (user == null) {
            user = new ArrayList<User>();
        }
        return this.user;
    }

    /**
     * Gets the value of the servicegroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the servicegroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServicegroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceGroup }
     * 
     * 
     */
    public List<ServiceGroup> getServicegroup() {
        if (servicegroup == null) {
            servicegroup = new ArrayList<ServiceGroup>();
        }
        return this.servicegroup;
    }

    /**
     * Gets the value of the org property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrg() {
        return org;
    }

    /**
     * Sets the value of the org property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrg(String value) {
        this.org = value;
    }

}
