//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 10:05:41 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://caas.kisst.org/2.0/template", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.kisst.caas._2_0.template;
