//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 10:05:41 AM CEST 
//


package org.kisst.caas._2_0.template;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Assignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assignment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="team" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="effectivedate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="principal" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="lead" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="rolename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="roletype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rolepackage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assignment")
public class Assignment {

    @XmlAttribute(name = "team")
    protected String team;
    @XmlAttribute(name = "effectivedate")
    protected String effectivedate;
    @XmlAttribute(name = "principal")
    protected Boolean principal;
    @XmlAttribute(name = "lead")
    protected Boolean lead;
    @XmlAttribute(name = "rolename")
    protected String rolename;
    @XmlAttribute(name = "roletype")
    protected String roletype;
    @XmlAttribute(name = "rolepackage")
    protected String rolepackage;

    /**
     * Gets the value of the team property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeam() {
        return team;
    }

    /**
     * Sets the value of the team property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeam(String value) {
        this.team = value;
    }

    /**
     * Gets the value of the effectivedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectivedate() {
        return effectivedate;
    }

    /**
     * Sets the value of the effectivedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectivedate(String value) {
        this.effectivedate = value;
    }

    /**
     * Gets the value of the principal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrincipal() {
        return principal;
    }

    /**
     * Sets the value of the principal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrincipal(Boolean value) {
        this.principal = value;
    }

    /**
     * Gets the value of the lead property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLead() {
        return lead;
    }

    /**
     * Sets the value of the lead property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLead(Boolean value) {
        this.lead = value;
    }

    /**
     * Gets the value of the rolename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * Sets the value of the rolename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolename(String value) {
        this.rolename = value;
    }

    /**
     * Gets the value of the roletype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoletype() {
        return roletype;
    }

    /**
     * Sets the value of the roletype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoletype(String value) {
        this.roletype = value;
    }

    /**
     * Gets the value of the rolepackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolepackage() {
        return rolepackage;
    }

    /**
     * Sets the value of the rolepackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolepackage(String value) {
        this.rolepackage = value;
    }

}
