//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 10:05:41 AM CEST 
//


package org.kisst.caas._2_0.template;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConnectionPointType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConnectionPointType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="socket"/>
 *     &lt;enumeration value="msmq"/>
 *     &lt;enumeration value="jms"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ConnectionPointType")
@XmlEnum
public enum ConnectionPointType {

    @XmlEnumValue("socket")
    SOCKET("socket"),
    @XmlEnumValue("msmq")
    MSMQ("msmq"),
    @XmlEnumValue("jms")
    JMS("jms"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    ConnectionPointType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConnectionPointType fromValue(String v) {
        for (ConnectionPointType c: ConnectionPointType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
