//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 10:05:41 AM CEST 
//


package org.kisst.caas._2_0.template;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bussoapnodeconfiguration" type="{http://caas.kisst.org/2.0/template}BusSoapNodeConfiguration"/>
 *         &lt;element name="wsi" type="{http://caas.kisst.org/2.0/template}WSI" maxOccurs="unbounded"/>
 *         &lt;element name="sc" type="{http://caas.kisst.org/2.0/template}ServiceContainer" maxOccurs="unbounded"/>
 *         &lt;element name="strategy" type="{http://caas.kisst.org/2.0/template}Strategy" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceGroup", propOrder = {
    "bussoapnodeconfiguration",
    "wsi",
    "sc",
    "strategy"
})
public class ServiceGroup {

    @XmlElement(required = true)
    protected BusSoapNodeConfiguration bussoapnodeconfiguration;
    @XmlElement(required = true)
    protected List<WSI> wsi;
    @XmlElement(required = true)
    protected List<ServiceContainer> sc;
    protected Strategy strategy;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the bussoapnodeconfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link BusSoapNodeConfiguration }
     *     
     */
    public BusSoapNodeConfiguration getBussoapnodeconfiguration() {
        return bussoapnodeconfiguration;
    }

    /**
     * Sets the value of the bussoapnodeconfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusSoapNodeConfiguration }
     *     
     */
    public void setBussoapnodeconfiguration(BusSoapNodeConfiguration value) {
        this.bussoapnodeconfiguration = value;
    }

    /**
     * Gets the value of the wsi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wsi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWsi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WSI }
     * 
     * 
     */
    public List<WSI> getWsi() {
        if (wsi == null) {
            wsi = new ArrayList<WSI>();
        }
        return this.wsi;
    }

    /**
     * Gets the value of the sc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceContainer }
     * 
     * 
     */
    public List<ServiceContainer> getSc() {
        if (sc == null) {
            sc = new ArrayList<ServiceContainer>();
        }
        return this.sc;
    }

    /**
     * Gets the value of the strategy property.
     * 
     * @return
     *     possible object is
     *     {@link Strategy }
     *     
     */
    public Strategy getStrategy() {
        return strategy;
    }

    /**
     * Sets the value of the strategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Strategy }
     *     
     */
    public void setStrategy(Strategy value) {
        this.strategy = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
