//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.21 at 10:05:41 AM CEST 
//


package org.kisst.caas._2_0.template;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Holds the details of a service container that should be created under the service group Note that if you deploy to a
 *         cluster it will create
 *       
 * 
 * <p>Java class for ServiceContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceContainer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bussoapprocessorconfiguration" type="{http://caas.kisst.org/2.0/template}BusSoapProcessorConfiguration"/>
 *         &lt;element name="cp" type="{http://caas.kisst.org/2.0/template}ConnectionPoint" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="automatic" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="machine" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ignorestrategy" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceContainer", propOrder = {
    "bussoapprocessorconfiguration",
    "cp"
})
public class ServiceContainer {

    @XmlElement(required = true)
    protected BusSoapProcessorConfiguration bussoapprocessorconfiguration;
    @XmlElement(required = true)
    protected List<ConnectionPoint> cp;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "automatic")
    protected Boolean automatic;
    @XmlAttribute(name = "machine")
    protected String machine;
    @XmlAttribute(name = "ignorestrategy")
    protected Boolean ignorestrategy;

    /**
     * Gets the value of the bussoapprocessorconfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link BusSoapProcessorConfiguration }
     *     
     */
    public BusSoapProcessorConfiguration getBussoapprocessorconfiguration() {
        return bussoapprocessorconfiguration;
    }

    /**
     * Sets the value of the bussoapprocessorconfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusSoapProcessorConfiguration }
     *     
     */
    public void setBussoapprocessorconfiguration(BusSoapProcessorConfiguration value) {
        this.bussoapprocessorconfiguration = value;
    }

    /**
     * Gets the value of the cp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConnectionPoint }
     * 
     * 
     */
    public List<ConnectionPoint> getCp() {
        if (cp == null) {
            cp = new ArrayList<ConnectionPoint>();
        }
        return this.cp;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the automatic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutomatic() {
        return automatic;
    }

    /**
     * Sets the value of the automatic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutomatic(Boolean value) {
        this.automatic = value;
    }

    /**
     * Gets the value of the machine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMachine() {
        return machine;
    }

    /**
     * Sets the value of the machine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMachine(String value) {
        this.machine = value;
    }

    /**
     * Gets the value of the ignorestrategy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIgnorestrategy() {
        return ignorestrategy;
    }

    /**
     * Sets the value of the ignorestrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIgnorestrategy(Boolean value) {
        this.ignorestrategy = value;
    }

}
